### PR TITLE
Resolved errors in Xcode 6.3

### PR DESCRIPTION
**Pull request by bhstahl**
@alfiehanssen These are the `abs()` -> `fabs()` changes we ran into yesterday which fixed things in Xcode 6.3. I also had errors in AFNetworking when building VIMNetworking on its own, so I updated to the latest release and it resolved.

### CODE REVIEW

**Comment by samidaik00** [comment]
Hi,
Yes i am running into the exact same 2 issues. think this pull request should be merged in

**Comment by alfiehanssen** [comment]
Cool, will review either this afternoon or Monday and merge, thanks for the pr @bhstahl

**Comment by samidaik00** [comment]
@alfiehanssen Hi, have you maybe had a chance to give a look at @bhstahl stuff ?

**Comment by alfiehanssen** [comment]
@bhstahl can you please revise the PR to compare against DEV branch?

**Comment by alfiehanssen** [comment]
See [contributing.md](https://github.com/vimeo/VIMNetworking/blob/master/CONTRIBUTING.md) for details...

**Comment by alfiehanssen** [comment]
@samidaik00 I'll merge momentarily. But it'll be merged into the DEV branch. I recommend working off of the DEV branch for now. We make releases roughly every 3 weeks, corresponding to our in-house sprint schedule (new release at the end of each sprint). The next release will be 1 week from this Friday.

**Comment by bhstahl** [comment]
Closing in favor of #15 which properly updates the AFNetworking submodule

**Comment by samidaik00** [comment]
ok great, I'm working of the DEV branch in my repo and no build errors... but i am now having linking duplicate symbols issues as my project already uses AFNetworking (through Cocoapods) ... any suggestions of should I (or we, as I may not be alone) do ?
Kind regards

**Comment by alfiehanssen** [comment]
Hey @samidaik00, we've got a cocoapods branch in the works, we're shooting to merge it next sprint, which means it'll hit dev roughly 2 wks from now.

**Comment by samidaik00** [comment]
Ha great.. My next question was going to be "Are you guys maybe gonna bring the project into Cocoapods..."
Looking forward .
cheers

**Comment by samidaik00** [comment]
Hi @alfiehanssen  - Just wondering about any updates on the cocoapods thing we talked about ..?
Otherwise if there is another way I could use the lib within my project which already has AFNetworking as I have not managed to do so ...
Cheers

**Comment by alfiehanssen** [comment]
Hey @samidaik00, this work is scheduled for next week. Stay tuned...

**Comment by samidaik00** [comment]
great... REALLY Looking forward...  :)

**Comment by samidaik00** [comment]
Great stuff for the Cocoapods version of the lib guys... Now integrating & using smoothly in my project....
@alfiehanssen I have one question regarding one thing I am trying to achieve ... I need to pass the OAuth Acesss token bck to my server so my backend retrieves and treat the data on behalf of my iOS app ... I have a prototype working which is currently using a OAuth token generated from the the developer.vimeo platform ....

Is there any way to get this token from the VIMNetworking SDK (and also the vimeo userID) once the user authenticated ?
Cheers

**Comment by alfiehanssen** [comment]
The unique id for a user is the user's `uri`. You can access this like so:

`[VIMSession sharedSession].authenticatedUser.uri`

You can access the token like so:

`[VIMSession sharedSession].account.credential.accessToken`

**Comment by samidaik00** [comment]
Amazing, got it! thanks for the prompt answer

**Pull request closed without merging**
